server:
  port: 8080
  servlet:
    context-path: "/"

logging:
  level:
    org:
      springframework:
        web: DEBUG

spring:
  datasource:
    url: jdbc:h2:file:~/craft
    username: sa
    password:
    driver-class-name: org.h2.Driver
    tomcat:
      max-active: 10
      max-idle: 0
      max-wait: 1000
      min-evictable-idle-time-millis: 100
      min-idle: 8
      time-between-eviction-runs-millis: 1
  data:
    rest:
      base-path: "/api"
  h2:
    console:
      enabled: true

